src/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogIndexView.as_view(), name='index'),
    path('<category>/', views.PostByCategoryListView.as_view(), name='category'),
    path('<category>/<slug:slug>', views.PostDetailView.as_view(), name='detail'),
]

src/gregcsokas/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from core import views as core_views

urlpatterns = [
    path('', core_views.SinglePageView.as_view(), name='index'),
    path('about/', core_views.SinglePageView.as_view(), name='about'),
    path('gc-admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/blog/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from martor.models import MartorField

STATUSES = (
    ('DR', _('Draft')),
    ('PU', _('Published')),
    ('PR', _('Private'))
)


class Category(models.Model):
    """ Category model"""

    name = models.CharField(_('category name'), max_length=50)
    slug = models.SlugField(_('category slug'), max_length=50, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(_('tag'), max_length=25, blank=True)

    class Meta:
        ordering = ['-name']

    def __str__(self):
        return self.name


class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ContentModel(TimeStampModel):
    content = MartorField(_('content'))

    class Meta:
        abstract = True


class Post(ContentModel):
    author = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_staff': True},
                               null=True, related_name='blog_posts')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    title = models.CharField(_('post title'), max_length=100)
    slug = models.SlugField(_('post slug'), max_length=105, blank=True, unique=True)
    head_image = models.ImageField(upload_to='uploads/', default='no-img')
    status = models.CharField(_('post status'), choices=STATUSES, max_length=20, default='draft', db_index=True)
    pub_date = models.DateTimeField(_('publication date'), default=timezone.now)
    comments = models.BooleanField(_('allow comments'), default=True)
    view_count = models.IntegerField(_('sum of views'), default=0)
    favs = models.IntegerField(_('sum of favourites'), default=0)

    class Meta:
        unique_together = ('slug', 'created')
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    @property
    def post_slug(self):
        return "{}/{}".format(self.category.slug, self.slug)


class Comment(models.Model):
    pass

src/core/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.translation import ugettext_lazy as _

from martor.models import MartorField


class FilterUrl(models.Model):
    filter_url = models.CharField(_('text type url field for metadata'),
                                  max_length=100, unique=True, blank=True, null=True)

    class Meta:
        abstract = True


class MetaData(FilterUrl):
    title = models.CharField(_('page title'), max_length=60)
    viewport = models.CharField(_('viewport'), max_length=100, default='width=device-width, initial-scale=1')  # noqa
    description = models.CharField(_('page description'), max_length=165)
    keywords = ArrayField(models.CharField(max_length=10, blank=True), size=8)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, limit_choices_to={'is_staff': True})  # noqa

    class Meta:
        pass

    def __str__(self):
        return self.title


class SinglePage(FilterUrl):
    title = models.CharField(_('page title'), max_length=60)
    content = MartorField(_('page content'))

    class Meta:
        pass

    def __str__(self):
        return self.title

src/blog/views.py
# -*- coding: utf-8 -*-
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views import generic
from django.utils import timezone

from blog.models import Post


logger = logging.getLogger('grecsokas' + __name__)


class BlogIndexView(generic.ListView):
    template_name = 'blog/post_list.html'
    queryset = Post.objects.all()

    def get_queryset(self, **kwargs):
        queryset = super(BlogIndexView, self).get_queryset().prefetch_related('category').prefetch_related('author')
        if not self.request.user.is_staff:
            queryset = queryset.exclude(pub_date__gte=timezone.now()) \
                .exclude(status='DR') \
                .exclude(status='PR')

        return queryset


class PostByCategoryListView(generic.ListView):
    template_name = 'blog/post_list.html'
    queryset = Post.objects.all().prefetch_related('category').prefetch_related('author')

    def get_queryset(self, **kwargs):
        queryset = super(PostByCategoryListView, self).get_queryset()\
            .filter(category__name__iexact=self.kwargs['category'])
        if not self.request.user.is_staff:
            queryset = queryset.exclude(pub_date__gte=timezone.now()) \
                .exclude(status='DR') \
                .exclude(status='PR')

        return queryset


class PostDetailView(generic.DetailView):
    template_name = 'blog/post_detail.html'
    queryset = Post.objects.all()

    def get_queryset(self, **kwargs):
        queryset = super(PostDetailView, self).get_queryset()\
            .prefetch_related('category').prefetch_related('author') \
            .filter(slug=self.kwargs['slug'])
        if not self.request.user.is_staff:
            queryset = queryset.exclude(pub_date__gte=timezone.now()) \
                .exclude(status='DR') \
                .exclude(status='PR')

        return queryset

    def get_object(self, queryset=None):
        queryset = self.get_queryset()

        try:
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise Http404("No post matches the given query.")

        return obj

src/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.views import generic

from .models import SinglePage


class SinglePageView(generic.TemplateView):
    template_name = 'core/simple_view.html'

    def get_context_data(self, **kwargs):
        context = super(SinglePageView, self).get_context_data(**kwargs)
        context['content'] = get_object_or_404(SinglePage, filter_url=self.request.path)

        return context

src/core/templates/simple_view.html
{% extends 'base/base.html' %}
{% load martortags %}

{% block content %}
  <section>
    <h3>{{ content.title }}</h3>
    {{ content.content|safe_markdown }}
  </section>
{% endblock %}

src/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  {% include 'base/head.html' %}

</head>
<body class="container col">

  {% include 'base/header.html' %}

  {% block content %}

  {% endblock %}

  {% include 'base/footer.html' %}

	<div class="status-bar-offset navbar-fixed-bottom">
    <span class="label label-primary" id="browserWindowWidth">- px</span>
    <span class="label label-primary" id="browserWindowHeight">- px</span>
	</div>

	<script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{#  <script async src="https://pro.fontawesome.com/releases/v5.0.10/js/light.js" integrity="sha384-rv/n2A+UxOzR1qs4wrcOtJ7Ai5Hcn3QQ8tvEkOo5lCvqCD3xwpeO3KZP18JpSXr3" crossorigin="anonymous"></script>#}
{#  <script async src="https://pro.fontawesome.com/releases/v5.0.10/js/brands.js" integrity="sha384-OwdVp9K/baqiXthTvRnYzMcsTaqwG19SfDkTRc/GBIhK9eYlWVVBEvLlueA0STAP" crossorigin="anonymous"></script>#}

	<script>
			$.noConflict();


			width = jQuery( window ).width();
			jQuery('#browserWindowWidth').html(width + " px");

			height = jQuery(this).height();
			jQuery('#browserWindowHeight').html(height + " px");

			/**
			 *
			 * ResizeTool
			 *
			 **/
			jQuery(window).resize(function () {

					if (jQuery(this).width() != width) {
							width = jQuery(this).width();
							jQuery('#browserWindowWidth').html(width + " px");
					}

					if (jQuery(this).height() != height) {
							height = jQuery(this).height();
							jQuery('#browserWindowHeight').html(height + " px");
					}

			});
	</script>

	<style type="text/css">

			.label-primary {
					background-color: #428bca;
			}

			.label {
					border-radius: 0.25em;
					color: #fff;
					display: inline;
					font-size: 75%;
					font-weight: 700;
					line-height: 1;
					padding: 0.2em 0.6em 0.3em;
					text-align: center;
					vertical-align: baseline;
					white-space: nowrap;
			}

			.navbar-fixed-bottom {
					border-radius: 0;
					border-width: 1px 0 0;
					bottom: 0;
					margin-bottom: 0;
					left: 0;
					position: fixed;
					right: 0;
					z-index: 9999;
			}

	</style>

</body>
</html>

src/templates/base/footer.html
<footer class="container col-no-wrap">
  <div class="container row-no-wrap">
    {% for com in common %}
      <div>
        <h4>{{ com }}</h4>
        <p>{{ com.content|safe }}</p>
      </div>
    {% endfor %}
    </div>
    <div class="copyright-box">
        <hr />
            <span class="copyright-text">
                <i class="fal fa-copyright fa-xs" data-fa-transform="up-10"></i> Greg Csokas {% now "Y" %}
            </span>
    </div>
</footer>

src/templates/base/head.html
{% load static %}

<meta content="text/html" charset="UTF-8" />
<meta name="viewport" content="{{ meta.viewport }}">
<title>{{ meta.title }}</title>
<meta name="description" content="{{ meta.description }}" />
<meta name="keywords" content="{{ meta.keywords }}" />
<meta name="author" content="{{ meta.author }}" />

{#<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.0.13/css/light.css" integrity="sha384-d8NbeymhHpk+ydwT2rk4GxrRuC9pDL/3A6EIedSEYb+LE+KQ5QKgIWTjYwHj/NBs" crossorigin="anonymous">#}
{#<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.0.13/css/fontawesome.css" integrity="sha384-LDuQaX4rOgqi4rbWCyWj3XVBlgDzuxGy/E6vWN6U7c25/eSJIwyKhy9WgZCHQWXz" crossorigin="anonymous">#}

<link rel="stylesheet" type="text/css" href="{% static 'css/golden_compass.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/colors.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/mediaquery.css" %}" />

src/templates/base/header.html
{% load i18n %}

  <nav class="container row-no-wrap">
    <ul class="menu container ju-c">
      <li class="menu-item"> <a class="home" href="/">Greg Csokas</a></li>
      <li class="menu-item"> <a href="/about/">Bio</a> </li>
{#      <li class="menu-item"> <a href="/cv/" disabled>CV</a> </li>#}
{#      <li class="menu-item"> <a href="/portfolio/" disabled>Portfolio</a> </li>#}
      <li class="menu-item"> <a href="/lab/">Lab</a>
        <ul class="container col-no-wrap sub-menu">
          {% if not categories %}
            <li class="">{% trans "no categories"|capfirst %}</li>
          {% else %}
            {% for category in categories %}
              <li class="sub-menu-item"> <a href="{% url 'blog:index' %}{{ category.slug }}/">{{ category.name }}</a> </li>
            {% endfor %}
          {% endif %}
        </ul>
      </li>
{#      <li class="menu-item search">#}
{#        <form class="container row-no-wrap" role="search" method="get" action="">#}
{#          <input class="search_text" type="text" name="search" id="search" placeholder="Search"/>#}
{#          <button class="search-button" type="submit"><i class="fal fa-search"></i></button>#}
{#        </form>#}
{#      </li>#}
{#      <li class="menu-item login">#}
{#        {% if user.is_authenticated %}#}
{#          <a href="/settings/"><i class="fal fa-sliders-h"></i></a>#}
{#        {% else %}#}
{#          <a href="/login/"><i class="fal fa-sign-in-alt"></i></a>#}
{#        {% endif %}#}
{#      </li>#}
{#      {% if user.is_authenticated %}#}
{#        <li class="menu-item login">#}
{#          <a href="/logout/"><i class="fal fa-sign-out-alt"></i></a>#}
{#        </li>#}
{#      {% endif %}#}
    </ul>
  </nav>